"""
Custom Prometheus metrics for OmniDigest business logic.
OmniDigest 业务逻辑的自定义 Prometheus 指标。
"""
from prometheus_client import Counter, Gauge, Histogram

# ==========================
# Request Metrics
# ==========================

# Request duration histogram (auto-generated by instrumentator)
# Additional custom histogram for API endpoints
api_request_duration = Histogram(
    'api_request_duration_seconds',
    'API request duration in seconds',
    ['method', 'endpoint', 'status'],
    buckets=(0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1.0, 2.5, 5.0, 7.5, 10.0)
)

# ==========================
# Cache Metrics
# ==========================

cache_hits_total = Counter(
    'cache_hits_total',
    'Total number of cache hits',
    ['cache_type']
)

cache_misses_total = Counter(
    'cache_misses_total',
    'Total number of cache misses',
    ['cache_type']
)

cache_hit_ratio = Gauge(
    'cache_hit_ratio',
    'Cache hit ratio (0-1)',
    ['cache_type']
)

# ==========================
# Database Metrics
# ==========================

db_connections_active = Gauge(
    'db_connections_active',
    'Number of active database connections'
)

db_query_duration = Histogram(
    'db_query_duration_seconds',
    'Database query duration in seconds',
    ['query_type'],
    buckets=(0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0)
)

# ==========================
# LLM Metrics
# ==========================

llm_tokens_used_total = Counter(
    'llm_tokens_used_total',
    'Total number of LLM tokens used',
    ['model', 'provider', 'purpose']
)

llm_requests_total = Counter(
    'llm_requests_total',
    'Total number of LLM requests',
    ['model', 'provider', 'status']
)

llm_request_duration = Histogram(
    'llm_request_duration_seconds',
    'LLM request duration in seconds',
    ['model', 'provider'],
    buckets=(0.1, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0, 60.0)
)

# ==========================
# Job Metrics
# ==========================

job_execution_count = Counter(
    'job_execution_count',
    'Total number of job executions',
    ['job_name', 'status']
)

job_failure_count = Counter(
    'job_failure_count',
    'Total number of job failures',
    ['job_name', 'error_type']
)

job_duration = Histogram(
    'job_duration_seconds',
    'Job execution duration in seconds',
    ['job_name'],
    buckets=(1.0, 5.0, 10.0, 30.0, 60.0, 300.0, 600.0, 1800.0, 3600.0)
)

# ==========================
# Data Processing Metrics
# ==========================

articles_processed_total = Counter(
    'articles_processed_total',
    'Total number of articles processed',
    ['source', 'status']
)

news_fetched_total = Counter(
    'news_fetched_total',
    'Total number of news items fetched',
    ['source', 'status']
)

# ==========================
# A-Share Market Metrics
# ==========================

astock_analysis_count = Counter(
    'astock_analysis_count',
    'Total number of A-share analysis runs',
    ['analysis_type', 'status']
)

astock_api_calls_total = Counter(
    'astock_api_calls_total',
    'Total number of A-share API calls',
    ['endpoint', 'status']
)
